# -*- coding: utf-8 -*-
"""Ejercicios_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NzhQLYLuvWJvcSxkygQjWQYDVBHqwZNi
"""

import streamlit as st

st.write('Hello, *World!* :sunglasses:')